baseURL: https://thklein.io/
languageCode: en-us
title: thklein.io
theme: "PaperMod"

enableRobotsTXT: true
enableEmoji: true
enableInlineShortcodes: true
ebanleGitInfo: true

params:
  title: thklein.io
  description: Thorsten Klein Software Development & Operations
  author: Thorsten Klein

  label:
    icon: /logo/logo_only_v01.svg

  defaultTheme: auto

  # post settings
  showReadingTime: true
  showShareButtons: true
  showCodeCopyButtons: true
  showFullTextInRSS: true

  # others

  assets:
    favicon: favicons/favicon.ico
    favicon16x16: favicons/favicon-16x16.png
    favicon32x32: favicons/favicon-32x32.png
    apple_touch_icon: favicons/apple-icon.png
    safari_pinned_tab: favicons/apple-icon.png

  socialIcons:
    - name: email
      url: mailto:tk@thklein.io
    - name: twitter
      url: https://twitter.com/iwilltry42
    - name: github
      url: https://github.com/iwilltry42
    - name: linkedin
      url: https://www.linkedin.com/in/thorsten-klein-b39520114/
    - name: xing
      url: https://www.xing.com/profile/Thorsten_Klein141

  profileMode:
    enabled: true
    title: Thorsten Klein
    subtitle: |
      ### Software Development & Operations
      ----

      Welcome to the business site of my life, where I help people, teams and companies to make the best out of their infrastructure and development workflows.
    imageUrl: "logo/logo_only_v01.svg"
    #imageWidth: 2056px
    # imageHeight: 1124px
    buttons:
      - name: Portfolio
        url: "portfolio"
      - name: Blog
        url: "blog"
      - name: Personal Site
        url: "https://iwilltry42.dev"

markup:
  highlight:
    codeFences: true
    lineNos: true
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      hardwraps: true
      unsafe: true

menu:
  main:
    - name: Portfolio
      url: portfolio
      pre: '<i class="far fa-address-card"></i> '
      weight: 1
    - name: Blog
      url: blog
      pre: '<i class="far fa-comment-alt"></i> '
      weight: 2
    - name: Personal Site
      url: https://iwilltry42.dev
      pre: '<i class="far fa-user"></i> '
      weight: 3

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: false
  vimeo:
    disable: true
  youtube:
    disable: true